repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0  # Use the latest stable Black version.  Check for updates!
    hooks:
    -   id: black
        language_version: python3.9  # Match your project's Python version!
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use a recent version
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace 